catalogues: [personal]
description: "Example FW (OvS + Ryu) + IDS (Snort) service"
maintainer: "Manuel Peuster, Paderborn University, manuel.peuster@uni-paderborn.de, Steven Van Rossem, steven.vannrossem@intec.ugent.be"
name: sonata-fw-dpi-service
publish_to: [personal]
vendor: eu.sonata-nfv.package
version: '0.1'
